spring:
  application:
    name: sistema-mei

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update

    show-sql: true

    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope: profile, email

server:
  port: 8080

api:
  security:
    token:
      secret: ${JWT_SECRET}
  cors:
    origem: ${CORS_ORIGIN:http://localhost:5173}

frontend:
  url: ${FRONTEND_URL:http://localhost:5173}
